module.exports = {
	poppins_Thin: "Poppins_100Thin",
	poppins_Thin_Italic: "Poppins_100Thin_Italic",
	poppins_ExtraLight: "Poppins_200ExtraLight",
	poppins_ExtraLight_Italic: "Poppins_200ExtraLight_Italic",
	poppins_Light: "Poppins_300Light",
	poppins_Light_Italic: "Poppins_300Light_Italic",
	poppins_Regular: "Poppins_400Regular",
	poppins_Regular_Italic: "Poppins_400Regular_Italic",
	poppins_Medium: "Poppins_500Medium",
	poppins_Medium_Italic: "Poppins_500Medium_Italic",
	poppins_SemiBold: "Poppins_600SemiBold",
	poppins_SemiBold_Italic: "Poppins_600SemiBold_Italic",
	poppins_Bold: "Poppins_700Bold",
	poppins_Bold_Italic: "Poppins_700Bold_Italic",
	poppins_ExtraBold: "Poppins_800ExtraBold",
	poppins_ExtraBold_Italic: "Poppins_800ExtraBold_Italic",
	poppins_Black: "Poppins_900Black",
	poppins_Black_Italic: "Poppins_900Black_Italic",

	noto_sans_Regular: "NotoSans_400Regular",
	noto_sans_Regular_Italic: "NotoSans_400Regular_Italic",
	noto_sans_Medium: "NotoSans_500Medium",
	noto_sans_Medium_Italic: "NotoSans_500Medium_Italic",
	noto_sans_SemiBold: "NotoSans_600SemiBold",
	noto_sans_SemiBold_Italic: "NotoSans_600SemiBold_Italic",
};
